select 
{% if target.name == 'dev' %} top 0 {% endif %}
ID,
Code,
Name,
Description,
PublishType,
Activate,
IsDeleted,
CreatedDate,
ParentID,
ADN,
LastChildADN,
BaseSource,
LastUpdateBase,
PercentProfit,
IsDisplay,
Color,
IsSBAService,
IsSBARetail,
IsSBALicense,
IsSBAServiceRetail,
{{ adapter.quote("dv_record_source") }},
        {{ adapter.quote("dv_applied_date") }}
from {{ source('DWH', 'Staging__CMIS_dbo_Branches') }}
