with source as (
      select * from {{ source('DWH', 'Staging__CMIS_dbo_Users') }}
),
renamed as (
    select
        {{ adapter.quote("ID") }},
        {{ adapter.quote("Email") }},
        {{ adapter.quote("Password") }},
        {{ adapter.quote("FirstName") }},
        {{ adapter.quote("LastName") }},
        {{ adapter.quote("EmployeeCode") }},
        {{ adapter.quote("Image") }},
        {{ adapter.quote("Thumb") }},
        {{ adapter.quote("DOB") }},
        {{ adapter.quote("Gender") }},
        {{ adapter.quote("Address") }},
        {{ adapter.quote("Phone") }},
        {{ adapter.quote("Active") }},
        {{ adapter.quote("Display") }},
        {{ adapter.quote("CreatedDate") }},
        {{ adapter.quote("CreatedByName") }},
        {{ adapter.quote("CreatedByID") }},
        {{ adapter.quote("TitleID") }},
        {{ adapter.quote("UserName") }},
        {{ adapter.quote("ContractDate") }},
        {{ adapter.quote("BeginWorkDate") }},
        {{ adapter.quote("LoyaltyYear") }},
      
        {{ adapter.quote("ModifiedDate") }},
        {{ adapter.quote("ModifiedByID") }},
        {{ adapter.quote("ModifiedByName") }},
        {{ adapter.quote("IsIntership") }},
        {{ adapter.quote("TitleText") }},
        {{ adapter.quote("WeightUser") }},
        {{ adapter.quote("EmployeeTypeID") }},
        {{ adapter.quote("About") }},
        {{ adapter.quote("Facebook") }},
        {{ adapter.quote("Twitter") }},
        {{ adapter.quote("GooglePlus") }},
        {{ adapter.quote("History") }},
        {{ adapter.quote("IsShowContact") }},
        {{ adapter.quote("KPIEmployeeTypeID") }},
        {{ adapter.quote("QuitDate") }},
        {{ adapter.quote("IsExternal") }},
        {{ adapter.quote("UserType") }},
        {{ adapter.quote("TokenKey") }},
        {{ adapter.quote("EndContractDate") }},
        {{ adapter.quote("HRCandidateID") }},
        {{ adapter.quote("AltEmail") }},
        {{ adapter.quote("AltPassword") }},
        {{ adapter.quote("AltUserName") }},
        {{ adapter.quote("SocialInsuranceNumber") }},
        {{ adapter.quote("Certificate") }},
        {{ adapter.quote("IdentityCardNumber") }},
        {{ adapter.quote("IdentityCardDate") }},
        {{ adapter.quote("IdentityCardPlace") }},
        {{ adapter.quote("CompanyID") }},
        {{ adapter.quote("LocationID") }},
        {{ adapter.quote("WorkTime") }},
        {{ adapter.quote("LevelText") }},
        {{ adapter.quote("Major") }},
        {{ adapter.quote("School") }},
        {{ adapter.quote("CurrentAdress") }},
        {{ adapter.quote("GroupTypeID") }},
        {{ adapter.quote("NextTokenKey") }},
        {{ adapter.quote("TokenExpiredDate") }},
        {{ adapter.quote("StatusSync") }},
        {{ adapter.quote("TimeSync") }},
        {{ adapter.quote("CountSync") }},
        {{ adapter.quote("CurrentURL") }},
        {{ adapter.quote("RoleID") }},
        {{ adapter.quote("GroupID") }},
        {{ adapter.quote("IsEmpNoMax") }},
        {{ adapter.quote("dv_record_source") }},
        {{ adapter.quote("dv_applied_date") }}

    from source
)
select * from renamed
  