with source as (
      select * from {{ source('DWH', 'Staging__CMIS_dbo_Customers') }}
),
renamed as (
    select
        {{ adapter.quote("ID") }},
        {{ adapter.quote("Code") }},
        {{ adapter.quote("TaxCode") }},
        {{ adapter.quote("Name") }},
        {{ adapter.quote("Address") }},
        {{ adapter.quote("Phone") }},
        {{ adapter.quote("Fax") }},
        {{ adapter.quote("Email") }},
        {{ adapter.quote("Website") }},
        {{ adapter.quote("Description") }},
        {{ adapter.quote("PublishType") }},
        {{ adapter.quote("Activate") }},
        {{ adapter.quote("IsDeleted") }},
        {{ adapter.quote("CreatedDate") }},
        {{ adapter.quote("CreatedByID") }},
        {{ adapter.quote("CreatedByName") }},
        {{ adapter.quote("ModifiedDate") }},
        {{ adapter.quote("ModifiedByID") }},
        {{ adapter.quote("ModifiedByName") }},
        {{ adapter.quote("BaseSource") }},
        {{ adapter.quote("LastUpdateBase") }},
        {{ adapter.quote("CustomerTypeID") }},
        {{ adapter.quote("HasCredit") }},
        {{ adapter.quote("CreditLimited") }},
        {{ adapter.quote("IndustryTypeID") }},
        {{ adapter.quote("DepartmentID") }},
        {{ adapter.quote("EnvironmentTypeID") }},
        {{ adapter.quote("ReasonsRefusal") }},
        {{ adapter.quote("Image") }},
        {{ adapter.quote("Thumb") }},
        {{ adapter.quote("AccountHolder") }},
        {{ adapter.quote("AccountNmuber") }},
        {{ adapter.quote("Bank") }},
        {{ adapter.quote("IsVip") }},
        {{ adapter.quote("IsPeersSI") }},
        {{ adapter.quote("IsCustomer") }},
        {{ adapter.quote("IsProvided") }},
        {{ adapter.quote("UserTAMID") }},
        {{ adapter.quote("IsHidden") }},
        {{ adapter.quote("PunishRatio") }},
        {{ adapter.quote("NameEng") }},
        {{ adapter.quote("AddressEng") }},
        {{ adapter.quote("ParentID") }},
        {{ adapter.quote("ParentCode") }},
        {{ adapter.quote("ADN") }},
        {{ adapter.quote("LastChildADN") }},
        {{ adapter.quote("AmIDs") }},
        {{ adapter.quote("Ams") }},
        {{ adapter.quote("SubIDs") }},
        {{ adapter.quote("Subs") }},
        {{ adapter.quote("ChildCompanies") }},
        {{ adapter.quote("CustomerTypeName") }},
        {{ adapter.quote("AccountGroupID") }},
        {{ adapter.quote("PartnerID") }},
        {{ adapter.quote("CountryID") }},
        {{ adapter.quote("CurrentURL") }},
        {{ adapter.quote("TimeSync") }},
        {{ adapter.quote("StatusSync") }},
        {{ adapter.quote("CountSync") }},
        {{ adapter.quote("DateGetData") }},
        {{ adapter.quote("CompanyCode") }},
        {{ adapter.quote("AccountGroupsCode") }},
        {{ adapter.quote("EnvironmentTypesCode") }},
        {{ adapter.quote("IndustryTypesCode") }},
        {{ adapter.quote("PartnerCode") }},
        {{ adapter.quote("CountryCode") }},
        {{ adapter.quote("DV_RECORD_SOURCE") }},
        {{ adapter.quote("DV_APPLIED_DATE") }}

    from source
)
select * from renamed
  