build_dv_for_cmc_use_automate_dv:
  target: dev
  outputs:
    dev:
      type: fabric
      threads: 32
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 'thrwspxeopkefcqhekjjo3xpve-ts7ajeugscoulf7v55pvrzntv4.datawarehouse.pbidedicated.windows.net'
      port: 1433
      database: DWH
      schema: dbo
      authentication: ServicePrincipal
      tenant_id: '3e69e399-73e4-42d4-8a07-2292976eefa9'
      client_id: 'cc7ec90c-0543-415d-8378-a5b21f26548e'
      client_secret: 'CkH8Q~zJTMD6n2TfDTaVqFuoUICQT-mN9Lty_ayE'